server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: micro-blog
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: true    # 是否将自己注册进eurekaServer，默认true
    fetchRegistry: true         #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:9527/eureka   #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    hostname: localhost

ribbon:
  ConnectTimeout: 4000
  ReadTimeout: 6000

#下划线转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true



#配置日志
logging:
  #此处存放日志的路径
  config: classpath:logback-spring.xml
  lever:
    root: INFO #root表示整个项目，也可单指定某个类（指定某个类放在logback文件指定也可以）

properties:
  ignoreAuthPath: []
  authPath: ['**/create*/**','**/update*/**','**/save*/**','**/delete*/**','**/migrate*/**','**/change*/**',]
