server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    register-with-eureka: true    # 是否将自己注册进eurekaServer，默认true
    fetchRegistry: true         #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:9527/eureka   #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    hostname: localhost

#配置日志
logging:
  #此处存放日志的路径
  path:
    config: classpath:logback-spring.xml
    #指定不同目录下的日志的级别
    #level:
    #com.shimain.springboot.mapper: INFO

#下划线转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true