server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      #很气，下面的routes项复制从来都不成功，只能手敲
      routes:
        - id: micro-blog         #路由的ID，没有固定规则但要求统一，建议配合服务名
          uri: lb://micro-blog #匹配后提供服务的路由地址
          predicates:
            - Path=/micro-blog/*     #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1

        - id: micro-blog-account         #路由的ID，没有固定规则但要求统一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://micro-blog-account #匹配后提供服务的路由地址
          predicates:
            - Path=/micro-blog-account/*     #断言，路径相匹配的进行路由





eureka:
  client:
    register-with-eureka: true    # 是否将自己注册进eurekaServer，默认true
    fetchRegistry: true         #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:9527/eureka   #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    hostname: localhost

#配置日志
logging:
  #此处存放日志的路径
  path:
    config: classpath:logback-spring.xml
    #指定不同目录下的日志的级别
    #level:
    #com.shimain.springboot.mapper: INFO